# Generated by Django 5.0.1 on 2024-02-04 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_do_something', 'Can do something custom')]},
        ),
    ]
